version: "3"
services:
  site:
    build: .
    image: movielist
    container_name: movielist
    ports:
      - 80:1337
    links:
      - mongodb
    depends_on:
      - mongodb
    volumes:
      - .:/app
  mongodb:
    image: mongo:4
    container_name: "mongodb"
    restart: always
    volumes:
      - mongo:/data/db
      - ./db-init/:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    expose:
      - '27017'
volumes:
  mongo: